### ISSUE TITLE
error on forms

### ISSUE THREAD

**Issue by MrScrudg** [CvvT/crawler_sqlmap#2]
hello, got such error:
ERROR:crawler.browser.headlessBrowser:input type HIDDEN not supported
Traceback (most recent call last):
  File "/root/crawler_sqlmap-master/crawler/browser/headlessBrowser.py", line 106, in finished
    self.onfinish(page)
  File "/root/crawler_sqlmap-master/crawler/browser/signal.py", line 13, in __call__
    fun(*args, **kwargs)
  File "/root/crawler_sqlmap-master/crawler/crawler.py", line 202, in parse_page
    for url, method, data in findPageForm(page.source_page, page.url):
  File "/root/crawler_sqlmap-master/crawler/util/findPageForm.py", line 81, in findPageForm
    data = extract_form_fields(form)
  File "/root/crawler_sqlmap-master/crawler/util/findPageForm.py", line 44, in extract_form_fields
    assert False, 'input type %s not supported' % input['type']
AssertionError: input type HIDDEN not supported
ERROR:crawler.crawler:skip this page

**Comment by CvvT** [comment]
Got this fixed. Thanks for your comment.
